### ISSUE TITLE
[EPIC] Improve and extend Kestra's GitHub Actions

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/deploy-action#16]
🔥 **Needs JavaScript SDK https://github.com/kestra-io/client-sdk/issues/111 to be done first.**

GitHub Actions haven't been modified for a long while and they'd benefit from a refactor to make it easier to:

- [ ] deploy flows to multiple namespaces --> currently, each Github actions is on a namespace level, meaning that you have to redefine the action in your GHA workflow for each namespace; it's a leftover from when we were handling flows as JSON files. Acc. to @Skraye, now that we handle flow as YAML with full source code, we can create a new command that takes all flows within a folder and deploys them to the namespace defined in the flow (even recursively so the user can organize their flows within multiple nested folders as they wish); we can offer the same functionality from the command line and from the GitHub Action.
- [ ] deploy namespace files (by pointing to a directory) to any namespaces
- [ ] explore additional actions based on Kestra's SDK/CLI that could help with some deployments e.g. trigger some flow (e.g. run a flow that will send a notification whenever the CI finishes)
- [ ] Add analytics, i.e. track usage of the Github Action

Deleting flows deleted in a GitHub repo is difficult without this being on the namespace level. We'll need to explore a stateful implementation as a Kestra service or system flow.

**Must-have requirement from Ludo:** base all GitHub Actions on the SDK/API (JavaScript SDK) instead of a Docker runtime.

**Comment by anna-geller** [comment]
Deleting flows deleted in a GitHub repo is difficult without this being on the namespace level. We'll need to explore a stateful implementation as a kestra service or system flow.
